### ISSUE TITLE
README.md link to meetup image is pointing to file that does not exist

### ISSUE THREAD

**Issue by JavaVista** [ProjectCodex/OpenSourceProjects#43]
If you take a look at your assets the image there has this `OpenSourceProjects/images/.meetupimage.jpg.icloud` and your `README` is looking for this `src="./images/meetupimage.jpg"`. I downloaded the `/.meetupimage.jpg.icloud` and it is an invalid file. 

From what I understand this an apple issue when backing up to the iCloud.  iCloud inserts a ghost/placeholder pending download/transfer completion.

I believed adding the correct image should fix this little issue.

**Comment by NickBelli** [comment]
Thanks for the report! @JavaVista - On investigation it looks like it was supposed to be a header image. I found some other assets within the repo that would work for that header, so I have made a few changes to the file and sent it for review by @mynar7 before issuing the PR for a fix.

**Comment by NickBelli** [comment]
This issue should be fixed by PR #42 . Admin please feel free to close the issue. Thank you!
